### PR TITLE
update example notebook

### PR DESCRIPTION
**Pull request by anilbey**
* delete unused imports
* fix typo
* add missing `n_processes=1` parameter

### CODE REVIEW

**Comment by wvangeit** [comment]
@anilbey , can you check why the tests are failing atm. Thx.

**Comment by anilbey** [comment]
`tox` was using this third party requirement that has the same name as the python built-in library although neither the built-in nor the third party package is used in BluePyMM's code.
https://pypi.org/project/pathlib/

**Comment by wvangeit** [comment]
It seems the 3.9 build stays stuck (restarted a couple of times)

**Comment by anilbey** [comment]
`tests/test_main::test_main_from_dir` test gets stuck in py39

**Comment by anilbey** [comment]
I couldn't reproduce it on our cluster with py3.9.7.

**Pull request merged**
