### PR TITLE
Support for hashed directory in BluePyMM

### PR DESCRIPTION
**Pull request by anilbey**

### CODE REVIEW

**Comment by arnaudon** [comment]
maybe the title is not so accurate

**Comment by wvangeit** [comment]
You can already merge without that, but do we have a test somewhere with an example apical points file ?

**Comment by arnaudon** [comment]
I don't think so, in the test the apical points are set to None afaik

**Comment by wvangeit** [comment]
Ok, so then please add the test (as I said you can already merge if it's urgent)

**Comment by anilbey** [comment]
I wrote the test for the `multieval` case by creating a new `setup` module with multieval enabled but this line of code below is making tests always use the previously loaded module.
https://github.com/BlueBrain/BluePyMM/blob/bc2e4609f5ec758e85d5c4fe01342b66302c76a2/bluepymm/tools.py#L110
I noticed some test cases are not providing the full morphology or emodels paths since they are relying on this lookup.
How should I proceed from here? Some possible solution are:
a) make the current `setup` module used in tests multieval enabled and change the rest of the test cases accordingly. (Btw. there are parts in the code not tested since they require multieval to be enabled)
b) have a separate directory and therefore `setup` module for the multieval tests. (This may require the modification of the sys.modules lookup above)
c) if the lookup stays (perhaps for performance reasons), we can change the names of the testing modules as well as some code to find a way around this.
d) During the teardown of the tests that are using the `setup` module, we unload the module. This way tests do not rely on each others modules and we bypass the lookup.
What do you think @wvangeit ?

**Comment by wvangeit** [comment]
For me as a first test you don't necessarily have to involve the setup scripts. If we could just test that the arguments are passed correctly it would already be good.
But having a new setup would of course be better. @anilbey it seems in that case a) is best?

**Comment by anilbey** [comment]
The a) option also reveals other parts of code that were not tested before like the lines below.
https://github.com/BlueBrain/BluePyMM/blob/bc2e4609f5ec758e85d5c4fe01342b66302c76a2/bluepymm/run_combos/calculate_scores.py#L121-L155

It has these issues below.
* setup.evaluator.create setup.evaluator.create method does not have a second parameter
* setup.evaluator.create method returns a single evaluator
* The hard coded response keys are not found in the test data like this one
`ValueError: Key mm.bpo_holding_current not found in responses: {'Step1.soma.v': <bluepyopt.ephys.responses.TimeVoltageResponse object at 0x7fe80dc2f310>}`

 @wvangeit  Is either this part of code or the test data outdated by any chance?

**Comment by wvangeit** [comment]
'Outdated' is a big word, but yeah we should adapt the setup example code to accommodate the changes in bluepymm.  But as far as I can see the 'old' evaluator would still work if "if hasattr(setup, 'multieval'):" is not true ?
For the case it is true, we would indeed need a newer setup.py. I think you can just use the old setup.py with modificiations:

> setup.evaluator.create setup.evaluator.create method does not have a second parameter
You can add that parameter, don't think the code needs to do anything specific with the value

> setup.evaluator.create method returns a single evaluator
You can return a list of evaluators

> The hard coded response keys are not found in the test data like this one
    ValueError: Key mm.bpo_holding_current not found in responses: {'Step1.soma.v': <bluepyopt.ephys.responses.TimeVoltageResponse object at 0x7fe80dc2f310>}
I guess you could mock a return value that has it

**Comment by anilbey** [comment]
Alright, I'm modifying the setup.

**Comment by anilbey** [comment]
As far as I understood, `holding_current` and `threshold_current` must be provided in the ephys protocol used in the `ehyps.evaluators.CellEvaluator` in order for the `CellEvaluator.run_protocol` to return these values.
Is there a simple way of creating a minimalist protocol that contains the holding & threshold currents?

**Comment by anilbey** [comment]
Right now setup module is using the `SweepProtocol`. The `StepProtocol` though mentions `holding_current` but not the `threshold_current`. Should I use the `StepProtocol` instead?

**Comment by wvangeit** [comment]
Yeah, the threshold_current is not being used in any of the classes of BluePyOpt. I assume you can use a mock value? You can use StepProtocol if you want.

**Comment by anilbey** [comment]
The test is added. I think the PR is ready to be merged now.

**Pull request merged**
