### PR TITLE
save pass/fail per metype in csv + comparaison of scores between runs

### PR DESCRIPTION
**Pull request by arnaudon**
This PR is for saving one extra file in extra_data folder for megating that contains the list of me models with the number of pass, error and failed cells. This is to allow for simpler comparison between various me-models.

### CODE REVIEW

**Comment by arnaudon** [comment]
please don't merge this PR, I will try to include more outputs for plotting/analysis, I'll let you know once I get something working.

**Comment by wvangeit** [comment]
Any update on this?

**Comment by arnaudon** [comment]
not yet, I didn't have time to get back to this to produce more plots. Do you mind leaving it here for a while? Or we can abandon it for now and I'll make a new PR once I have more to update?

**Comment by wvangeit** [comment]
Sure, np, was just wondering.

**Comment by arnaudon** [comment]
Just added a function to load the results from two different MM runs, and create violin plots of both sets of scores per emodel, to compare them.

**Pull request merged**
