### PR TITLE
upper case ASC, SWC compatible hoc template

### PR DESCRIPTION
**Pull request by AurelienJaquier**

### CODE REVIEW

**Review by darshanmandge — APPROVED** [review]
Thanks @AurelienJaquier ! 
For future reference, this change was necessary to allow uppercase morphology extension names used with the hoc templates. The change was also added to bluepyemodel with this [PR](https://github.com/BlueBrain/BluePyEModel/pull/127) where it worked with one of the morphologies with both "ASC" and "SWC" as extensions.

**Comment by arnaudon** [comment]
Hello, I'm a bit late here, but we usually rename the extension with morphology release, before running any opt, etc...

**Comment by arnaudon** [comment]
was this because you gave the name of the morph with .ASC, but the morph filename is with .asc ?

**Comment by darshanmandge** [comment]
I gave a morph .ASC and the morph name was also .ASC

**Pull request merged**
